benchmarks = '../benchmarks/core/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.ssa]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt ssa",
    "brili -p {args}",
]

[runs.valnum-dce]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt valnum dce",
    "brili -p {args}",
]

[runs.constprop-dce]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt constprop dce",
    "brili -p {args}",
]

[runs.valnum-constprop-dce]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt valnum constprop dce",
    "brili -p {args}",
]
