benchmarks = '../benchmarks/core/*.bril'
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt ssa",
    "brili -p {args}",
]

[runs.valnum-dce]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt ssa valnum dce",
    "brili -p {args}",
]

[runs.constprop-dce]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt ssa constprop dce",
    "brili -p {args}",
]

[runs.valnum-constprop-dce]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt ssa valnum constprop dce",
    "brili -p {args}",
]

[runs.vbe]
pipeline = [
    "bril2json",
    "_build/install/default/bin/opt ssa vbe",
    "brili -p {args}",
]
