(lang dune 3.16)

(name tylerhou)

(generate_opam_files true)

(package
 (name tylerhou)
 (depends ocaml dune core ppx_jane bril))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
